services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: imdb-sentiment-api
    ports:
      - "8005:8000"
    volumes:
      - ../models:/app/models
      - ../src:/app/src
    environment:
      - PROJECT_ROOT=/app
    restart: unless-stopped
    networks:
      - mlops-network

  # MLflow tracking server
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    container_name: imdb-mlflow
    ports:
      - "5005:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0
    volumes:
      - ../mlflow.db:/mlflow.db
      - ../mlruns:/mlruns
    networks:
      - mlops-network

  # Monitoring
  prometheus:
    image: prom/prometheus
    container_name: imdb-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9095:9090"
    networks:
      - mlops-network

  grafana:
    image: grafana/grafana
    container_name: imdb-grafana
    ports:
      - "3005:3000"
    depends_on:
      - prometheus
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge
